disabled_rules:
#----------Need addressing in the future---------------
- function_parameter_count
- cyclomatic_complexity
- block_based_kvo
- class_delegate_protocol
#-------------------------
# disable required unless we do cleanup to resolve
- type_body_length
- identifier_name
- file_length
- line_length
- function_body_length
- empty_enum_arguments
- todo
#---------------------------
opt_in_rules:
#- force_unwrapping
- anyobject_protocol
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- discouraged_assert
- discouraged_none_name
- empty_collection_literal
- empty_count
- empty_string
- explicit_init
- explicit_self
- fallthrough
#- implicit_return
- implicitly_unwrapped_optional
- indentation_width
- joined_default_parameter
- last_where
- legacy_multiple
- legacy_objc_type
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
- modifier_order
- multiline_function_chains
#- operator_usage_whitespace
- optional_enum_case_matching
- overridden_super_call
- override_in_extension
- prefer_self_in_static_references
- prefer_self_type_over_type_of_self
- prefer_zero_over_explicit_init
- redundant_nil_coalescing
#- redundant_type_annotation
- sorted_first_last
- sorted_imports
- static_operator
#- switch_case_on_newline
- trailing_closure
- unneeded_parentheses_in_closure_argument
- unowned_variable_capture
- unused_declaration
- unused_import
#- weak_delegate
#---------------------------
excluded:
- Carthage
- Pods
