disabled_rules:
#error producing
- cyclomatic_complexity
- file_length
- force_cast
- force_try
- function_body_length
- function_parameter_count
- identifier_name
- large_tuple
- line_length
- shorthand_operator
- type_body_length
- type_name
#Warning Producing
- unneeded_break_in_switch
- valid_ibinspectable
- vertical_parameter_alignment
- block_based_kvo
- class_delegate_protocol
- closing_brace
- closure_parameter_position
- comment_spacing
- compiler_protocol_init
- computed_accessors_order
#-------------------------
- empty_enum_arguments
#-------------------------
#-------------------------
#-------------------------
- todo

