disabled_rules:
#error producing
- cyclomatic_complexity
- file_length
- force_cast
- force_try
- function_body_length
- function_parameter_count
- identifier_name
- large_tuple
- line_length
- shorthand_operator
- type_body_length
- type_name
#Warning Producing
- unneeded_break_in_switch
- valid_ibinspectable
- vertical_parameter_alignment
- block_based_kvo
- class_delegate_protocol
- closing_brace
- closure_parameter_position
- comment_spacing
- compiler_protocol_init
- computed_accessors_order
#-------------------------
- control_statement
- deployment_target
- discouraged_direct_init
- duplicate_enum_cases
- duplicate_imports
- duplicated_key_in_dictionary_literal
- dynamic_inline
- empty_enum_arguments
- empty_parameters
- empty_parentheses_with_trailing_closure
#-------------------------
- for_where
- generic_type_name
- implicit_getter
- inclusive_language
- inert_defer
- is_disjoint
- mark
- multiple_closures_with_trailing_closure
- nesting
- no_fallthrough_only
#-------------------------
- no_space_in_method_call
- notification_center_detachment
- nsobject_prefer_isequal
- opening_brace
- orphaned_doc_comment
- private_over_fileprivate
- private_unit_test
- protocol_property_accessors_order
- reduce_boolean
- self_in_property_initialization
#-------------------------
- todo

