disabled_rules:
#----------Need addressing in the future---------------
- function_parameter_count
- cyclomatic_complexity
- block_based_kvo
- class_delegate_protocol
#-------------------------
#required unless we do cleanup to resolve
- type_body_length
- identifier_name
- file_length
- line_length
- function_body_length
- empty_enum_arguments
- todo
#---------------------------
opt_in_rules:
#- force_unwrapping
- anyobject_protocol
- contains_over_filter_is_empty
- contains_over_first_not_nil
- contains_over_range_nil_comparison
- discouraged_assert
- discouraged_none_name
- empty_collection_literal
- empty_count
- empty_string
- explicit_init
- explicit_self
- implicit_return
- implicitly_unwrapped_optional
- indentation_width
- joined_default_parameter
- last_where
- legacy_multiple
- legacy_objc_type
- let_var_whitespace
- literal_expression_end_indentation
- lower_acl_than_parent
#---------------------------
#- weak_delegate
- unused_import
- unneeded_parentheses_in_closure_argument
- trailing_closure
- static_operator
- redundant_nil_coalescing
- override_in_extension
- fallthrough

#---------------------------
excluded:
- Carthage
- Pods
