disabled_rules:
#error producing
- cyclomatic_complexity
- file_length
- force_cast
- force_try
- function_body_length
- function_parameter_count
- identifier_name
- large_tuple
- line_length
- shorthand_operator
- type_body_length
- type_name

#-------------------------
- empty_enum_arguments
- block_based_kvo
- class_delegate_protocol
- todo

